name: Get PageSpeed Insights
on:
  # schedule:
  # * is a special character in YAML so you have to quote this string
  # - cron:  '0 0 * * *' # 00:00 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  getpsresults:
    env:
      URL_TO_ANALYZE: <YOUR URL HERE>
      RESULTS_DIR: ps-reports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # This is a premade github action
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Create local changes
        run: | # Have to be sure a folder is present if not, make it
          npx psi-svg $URL_TO_ANALYZE $RESULTS_DIR/desktop.svg --strategy=desktop
          npx psi-svg $URL_TO_ANALYZE $RESULTS_DIR/mobile.svg --strategy=mobile
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "Updated Pagespeed results"
      - name: Push changes
        uses: ad-m/github-push-action@master # This is a premade github action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
